[package]
name = "peaq-rpc-core-types"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
# [TODO]
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.1.0"

[dependencies]
ethereum-types = "0.12.1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
