[package]
name = "peaq-rpc-primitives-txpool"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.6.0"

[dependencies]
ethereum = { version = "0.12.0", default-features = false, features = [ "with-codec" ] }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
sp-api = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.38", default-features = false }
sp-io = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.38", default-features = false }

[features]
default = [ "std" ]
std = [
	"ethereum/std",
	"sp-api/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
