[package]
name = "precompile-utils-macro"
authors = [ "PureStake" ]
description = ""
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
case = { workspace = true }
num_enum = { workspace = true, default-features = false }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
sha3 = { version = "0.8", default-features = false }
syn = { workspace = true, features = [ "extra-traits", "fold", "full", "visit" ] }

[dev-dependencies]
macrotest = { workspace = true, default-features = false }
trybuild = { workspace = true, default-features = false}

precompile-utils = { path = "../", features = [ "testing" ] }

fp-evm = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
