
name: Pull Request Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - name: "[Setup] Free Disk Space (insightsengineering/disk-space-reclaimer)"
        uses: insightsengineering/disk-space-reclaimer@v1.1.0

      - name: "[Setup] Linux Tools"
        run: sudo apt install -y cmake pkg-config libssl-dev build-essential clang libclang-dev curl protobuf-compiler

      - name: "[Setup] Rust"
        run: |
          TLCHN=nightly-2023-10-05
          curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $TLCHN
          rustup target add wasm32-unknown-unknown --toolchain $TLCHN
          cargo install cargo-expand --locked --version 1.0.34

      - name: Checkout Sources (actions/checkout)
        uses: actions/checkout@v3

      - name: "[Ceck] cargo fmt"
        run: |
          cargo fmt --check

      - name: "[Check] cargo test"
        run: |
          cargo test --release

      - name: "[Check] cargo clippy"
        run: |
          cargo clippy --release -- -Dwarnings
